--This file should contain the SQL to create a new TYPE called grocery and a new TABLE called shopping_list. The table will contain 6 columns and you will need to decide which SQL data types to use for each column. We'll supply you with a second SQL file that you will use to seed the shopping_list table items.

DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery AS ENUM (
  'Main',
  'Snack', 
  'Lunch', 
  'Breakfast'
);

CREATE TABLE IF NOT EXISTS shopping_list (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL, 
  price NUMERIC NOT NULL,
  date_added DATE DEFAULT now() NOT NULL, 
  checked BOOLEAN DEFAULT false NOT NULL,
  category grocery NOT NULL
);


